server:
  port: ${PORT:5301}

spring:
  cloud:
    bus:
      enabled: true
  rabbitmq:
    addresses: ${CLOUDAMQP_URL:amqp://drjoy.rep}
    ssl:
      enabled: false

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    non-secure-port-enabled: true
    non-secure-port: ${server.port}

turbine:
  app-config: WEB-FRONT,MOBILE-FRONT
  clusterNameExpression: "'default'"
  combine-host-port: true

#hystrix:
#  dashboard:
#    enable-ignore-connection-close-header: false
#  metrics:
#    enabled: true

management:
  security:
    enabled: false

security:
  basic:
    enabled: false

---
spring:
  profiles: cloud

  cloud:
    bus:
      enabled: true
  rabbitmq:
    ssl:
      enabled: false

management:
  security:
    enabled: true

security:
  basic:
    enabled: true
  user:
    name: user
    password: drjoy1115
